version: "3"
services: 
    maven:
        image: maven:latest
        container_name: maven
        #volumes: 
            #- ${PWD}:/usr/src/mymaven
        command: bash -c "git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello"
        links:
            - tomcat

    tomcat:
        image: tomcat:latest
        container_name: tomcat
        ports: 
            - "8080:8080"

    