version: "3"
services: 
    maven:
        image: maven:latest
        container_name: maven
        links:
            - tomcat

    tomcat:
        image: tomcat:latest
        container_name: tomcat
        ports: 
            - "8080:8080"

    