version: "3"
services: 
    maven:
        image: maven:3.3-jdk-8
        container_name: maven
        volumes: 
            - ${PWD}:/usr/src/mymaven/
        working_dir: /usr/src/mymaven/
        command: mvn verify -f boxfuse-sample-java-war-hello/pom.xml
        links:
            - tomcat

    tomcat:
        image: tomcat:latest
        container_name: tomcat
        volumes: 
            - ${PWD}/boxfuse-sample-java-war-hello:/usr/local/tomcat/webapps/
        ports: 
            - "8080:8080"

    