version: "3"
services: 
    maven:
        image: maven:latest
        container_name: maven
        volumes: 
            - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
        links:
            - tomcat

    tomcat:
        image: tomcat:latest
        container_name: tomcat
        ports: 
            - "8080:8080"

    